version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
       - db-data:/var/lib/postgresql/data
       - ./postgres/:/docker-entrypoint-initdb.d/
      
    ports:
      - "5432:5432"

 

  carsservice:
    build: RSOILab2/CarsService
    container_name: CarsService
    depends_on:
      postgres:
        condition: service_healthy
    environment:
          DATA_BASE_PORT: "5432"
          DATA_BASE_NAME: "postgres"
          DATA_BASE_USER: "postgres"
          DATA_BASE_PASS: "postgres"
          DATA_BASE_HOST: "postgres"
    ports:
      - "8070:8070"

  paymentservice:
    build: RSOILab2/PaymentService
    container_name: PaymentService
    depends_on:
      postgres:
        condition: service_healthy
    environment:
          DATA_BASE_PORT: "5432"
          DATA_BASE_NAME: "postgres"
          DATA_BASE_USER: "postgres"
          DATA_BASE_PASS: "postgres"
          DATA_BASE_HOST: "postgres"
    ports:
      - "8050:8050"

  rentalservice:
        build: RSOILab2/RentalService
        container_name: RentalService
        depends_on:
          postgres:
            condition: service_healthy
        environment:
          DATA_BASE_PORT: "5432"
          DATA_BASE_NAME: "postgres"
          DATA_BASE_USER: "postgres"
          DATA_BASE_PASS: "postgres"
          DATA_BASE_HOST: "postgres"
        ports:
          - "8060:8060"

  gatewayservice:
        build: RSOILab2/GatewayService
        container_name: GatewayService
        depends_on:
          postgres:
            condition: service_healthy
        environment:
          DATA_BASE_PORT: "5432"
          DATA_BASE_NAME: "postgres"
          DATA_BASE_USER: "postgres"
          DATA_BASE_PASS: "postgres"
          DATA_BASE_HOST: "postgres"
          CARS_SERVICE_HOST: "CarsService"
          CARS_SERVICE_PORT: "8070"
          PAYMENT_SERVICE_HOST: "PaymentService"
          PAYMENT_SERVICE_PORT: "8050"
          RENTAL_SERVICE_HOST: "RentalService"
          RENTAL_SERVICE_PORT: "8060"

        ports:
          - "8080:8080"

volumes:
  db-data: