version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
<<<<<<< HEAD

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 15s
      retries: 10
=======
 
>>>>>>> origin/master

  carsservice:
    build: lab2/carsservice
    container_name: carsservice
    depends_on:
      - postgres
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8070:8070"

  paymentservice:
    build: lab2/paymentservice
    container_name: paymentservice
    depends_on:
      - postgres
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8050:8050"

  rentalservice:
<<<<<<< HEAD
    build: lab2/rentalservice
    container_name: rentalservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8060:8060"

  gatewayservice:
    build: lab2/gatewayservice
    container_name: gatewayservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
      CARS_SERVICE_HOST: "carsservice"
      CARS_SERVICE_PORT: "8070"
      PAYMENT_SERVICE_HOST: "paymentservice"
      PAYMENT_SERVICE_PORT: "8050"
      RENTAL_SERVICE_HOST: "rentalservice"
      RENTAL_SERVICE_PORT: "8060"
=======
        build: RSOILab2/RentalService
        container_name: RentalService
        depends_on:
          - postgres
        environment:
          DATA_BASE_PORT: "5432"
          DATA_BASE_NAME: "postgres"
          DATA_BASE_USER: "postgres"
          DATA_BASE_PASS: "postgres"
          DATA_BASE_HOST: "postgres"
        ports:
          - "8060:8060"

  gatewayservice:
        build: RSOILab2/GatewayService
        container_name: GatewayService
        depends_on:
          - postgres
          - rentalservice
          - paymentservice
          - carsservice
        environment:
          DATA_BASE_PORT: "5432"
          DATA_BASE_NAME: "postgres"
          DATA_BASE_USER: "postgres"
          DATA_BASE_PASS: "postgres"
          DATA_BASE_HOST: "postgres"
          CARS_SERVICE_HOST: "CarsService"
          CARS_SERVICE_PORT: "8070"
          PAYMENT_SERVICE_HOST: "PaymentService"
          PAYMENT_SERVICE_PORT: "8050"
          RENTAL_SERVICE_HOST: "RentalService"
          RENTAL_SERVICE_PORT: "8060"
>>>>>>> origin/master

    ports:
      - "8080:8080"

volumes:
  db-data:
